name: Build Feature Branches

on:
  schedule:
    - cron: '5 * * * *'  # UTC timing
  workflow_dispatch:  # Allows manual triggering

jobs:
  find-feature-branches:
    runs-on: self-hosted  # Use your self-hosted runner
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all branches are fetched

      - name: Get all feature branches
        id: set-branches
        run: |
          FEATURE_BRANCHES=$(git branch -r | grep 'origin/feature-' | awk -F'/' '{print $2}' | jq -R -s -c 'split("\n")[:-1]')
          echo "Feature branches found: $FEATURE_BRANCHES"
          echo "branches=$FEATURE_BRANCHES" >> $GITHUB_OUTPUT

  process-feature-branches:
    needs: find-feature-branches
    runs-on: self-hosted  # Use your self-hosted runner
    strategy:
      matrix:
        branch: ${{ fromJson(needs.find-feature-branches.outputs.branches) }}
    steps:
      - name: Checkout feature branch ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Display the text file contents
        run: |
          cat test.txt || echo "File not found in branch ${{ matrix.branch }}"
