name: 24-hr-commit-check-build-feature-branch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    outputs:
      changed_branches: ${{ steps.filter.outputs.branches }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Feature Branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/feature-' | sed 's|origin/||' | tr '\n' ' ')
          echo "branches=$BRANCHES" >> $GITHUB_ENV

      - name: Find Branches with Recent Commits
        id: filter
        run: |
          RECENT_BRANCHES=()
          for BRANCH in ${{ env.branches }}; do
            LAST_COMMIT_TIME=$(git log -1 --format=%ct origin/$BRANCH)
            NOW=$(date +%s)
            DIFF=$((NOW - LAST_COMMIT_TIME))
            if [ $DIFF -le 86400 ]; then
              RECENT_BRANCHES+=("\"$BRANCH\"")
            fi
          done
          CHANGED_BRANCHES="[${RECENT_BRANCHES[*]}]"
          echo "branches=$CHANGED_BRANCHES" >> $GITHUB_OUTPUT

  trigger-jenkins:
    needs: check-commits
    runs-on: ubuntu-latest
    if: ${{ needs.check-commits.outputs.branches != '[]' }}
    steps:
      - name: Trigger Jenkins build for each branch
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          echo '${{ needs.check-commits.outputs.branches }}' | jq -c '.[]' > branches.txt
          while read branch; do
            CLEAN_BRANCH=$(echo $branch | tr -d '"')
            echo "Triggering Jenkins job for branch: $CLEAN_BRANCH"
            curl -X POST "http://127.0.0.1:8080/job/OnSchedule_Feature_Branch_Build//buildWithParameters?token=github-token&BRANCH=$CLEAN_BRANCH"
          done < branches.txt
