name: Nightly Build Of Multiple Feature Branches

on:
  schedule:
    - cron: '12 8 * * *'  
  push:
    branches:
      - feature-*  # Runs when any feature branch is pushed
  workflow_dispatch:  # Allows manual triggering

jobs:
  debug-cron:
    runs-on: self-hosted
    steps:
      - name: Show current time
        run: date -u
  
  check-file:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display contents of check.txt
        run: cat check.txt || echo "check.txt not found"
