name: Nightly Build Of Multiple Feature Branches

on:
  schedule:
    - cron: '21 8 * * *'  
  push:
    branches:
      - feature-*  # Runs when any feature branch is pushed
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-file:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Display contents of check.txt
        run: cat check.txt || echo "check.txt not found"
